### ISSUE TITLE
Use can't download dataset before saving query

### ISSUE THREAD

**Issue by arikfr** [EverythingMe/redash#68]
Because the query results url contains the query id, before saving the user can't download the dataset. 

We need to allow addressing query results without query id.

**Comment by arikfr** [comment]
Fixed.

**Comment by malinc854** [comment]
I am facing this issue in latest version

**Comment by malinc854** [comment]
issue persists.. I have added above changes in respective files under /opt/redash/current folder

**Comment by arikfr** [comment]
You can't just change the files, you need to rebuild the frontend code.

**Comment by malinc854** [comment]
@arikfr Hello,

Can you please guide me how can I build redash after making change.. Users are suffering and they cant download.
I did
1) create an EC2 using redash image (version 2)
2) upgrade redash to version 3
3) make changes in required files
4) install npm, node js and git
5) try to run npm build run on current folder

can't build this. there are errors. Please guide
